version: '3'

volumes:
  mysql-data:

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: on-failure  # 실패 시에만 재시작
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tstdb
      MYSQL_USER: tessbro
      MYSQL_PASSWORD: tess1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  app:
    image: seuo/tst-be-image
    container_name: tst-be
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tstdb
      SPRING_DATASOURCE_USERNAME: tessbro
      SPRING_DATASOURCE_PASSWORD: tess1234
