version: '3'
services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tstdb  # 데이터베이스 이름
      MYSQL_USER: tessbro
      MYSQL_PASSWORD: tess1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: seuo/tst-be-image
    container_name: tst-be
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tstdb?allowPublicKeyRetrieval=true&useSSL=false  # 데이터베이스 이름 수정
      SPRING_DATASOURCE_USERNAME: tessbro
      SPRING_DATASOURCE_PASSWORD: tess1234

volumes:
  mysql-data:
